### PR TITLE
Update comment and put init on top

### PR DESCRIPTION
**Pull request by DOsinga**
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/doppelganger/51)

### CODE REVIEW

**Comment by katbusch** [comment]
:lgtm:

Thanks! Not sure what's going on with the tests but  after #50 is merged they'll at least be easier to parse :)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/51#-:-KyY9sAN3ZXGYNsQj2ou:b80ly87)*

**Comment by DOsinga** [comment]
It seems to die on flake unrelated to this change:

./doppelganger/inputs.py:107:1: W293 blank line contains whitespace
./doppelganger/inputs.py:175:1: W293 blank line contains whitespace
./doppelganger/inputs.py:183:1: W293 blank line contains whitespace
./doppelganger/inputs.py:271:64: W292 no newline at end of file
./doppelganger/listbalancer.py:134:5: E741 ambiguous variable name 'I'
./doppelganger/listbalancer.py:159:40: E741 ambiguous variable name 'I'
./doppelganger/scripts/download_allocate_generate.py:213:5: E722 do not use bare except'

deactivate && pyenv shell 3.6.1 && bash -c "$TESTCMD" returned exit code 1

Happy to fix those, except for the last one, since I am not sure which exception we expect in that situation.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/51#-:-KyYByakAAe81l79uHu6:btmon0v)*

**Comment by katbusch** [comment]
I would try rebasing on master since the circle configs have changed today

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/51#-:-KyYb03Peta0GvSkcvCa:bbbmon)*

**Comment by DOsinga** [comment]
Great, works now!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/51#-:-Kya_f4OFfinpQFlXl6n:b-oe8ie3)*

**Pull request merged**
