### PR TITLE
Add household_id, factor out col names

### LINKED ISSUE #27: Household indexing is confusing
Right now households are unique by the (tract, serialno, repeatno) tuple.  They should just have a unique ID

### PR DESCRIPTION
**Pull request by katbusch**
This fixes #27, not in the requested way but in a cheap way that we can change later if we want.  I also moved a few strings into the inputs file as constants to make the code easier to write/maintain

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/doppelganger/35)

### CODE REVIEW

**Comment by katbusch** [comment]
[Create an initial population generator [3 days]](https://trello.com/c/owvjiBLK/63-create-an-initial-population-generator-3-days)

**Comment by nikisix** [comment]
The actual code looks and runs well. However, in order for this to be a unique_id, we should use the full tract id, including its state and county components.
I.e.
```
STATEFP  COUNTYFP  TRACTCE  PUMA5CE
01       001       020100   02100
01       001       020200   02100
01       001       020300   02100
01       001       020400   02100
01       001       020500   02100
01       001       020600   02100
01       001       020700   02100
01       001       020801   02100
01       001       020802   02100
```
Ideally we'd have tract_ids that look more like: "01001020802" than "20802", which is what I'm ending up with right now after generating synth households.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/35#-:-KskBFVnqz3rZx2WWrI4:bg0vof0)*

**Comment by nikisix** [comment]
I also realize, this may very well be outside of the purview of this push

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/35#-:-KskCngSlq75kvNF9Ei_:b45fhmh)*

**Comment by katbusch** [comment]
Ah I got it.  Okay, I agree that is outside the purview of this.  We should add state & county throughout our code and then we can tie it into the unique ID.  I will file a separate issue for that

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/35#-:-KskMf2HmGlLnja7O4Ql:bqnoznc)*

**Comment by katbusch** [comment]
Made #36

**Comment by nikisix** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/35#-:-KsnlqflQzymkbWm5oW1:bnfp4nl)*

**Pull request merged**
