### PR TITLE
Install pomegranate from wheel and update CircleCI setup

### PR DESCRIPTION
**Pull request by bnaul**
This combines a couple of things:
- Bump pomegranate to 0.8.1 (uses the new wheels that were just uploaded which should avoid the annoying installation problems)
- Move requirements into requirements.txt
- Update to the new CircleCI 2.0 config (this could be separated/removed, I just figured I might as well change it while I was in there; the tests run faster now since 2.7 and 3.6 happen in parallel)

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/doppelganger/50)

### CODE REVIEW

**Comment by katbusch** [comment]
:fireworks: 

Sweet!

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[requirements.txt, line 4 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-KyXgEc35fyBi-EXM5Y5:-KyXgEc35fyBi-EXM5Y6:b-78eot5) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/353d601959c3dd3c9f6bb82b092037f140d9ee09/requirements.txt#L4)):*
> ```
> numpy>=1.11.0
> pandas>=0.19.0
> pomegranate==0.8.1
> ```

Do we still need to pin the version?  I guess future ones won't have wheels

---

*[.circleci/config.yml, line 1 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-KyXhUzsiUKBa6IFPz2A:-KyXhUzsiUKBa6IFPz2B:bb77rlh) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/353d601959c3dd3c9f6bb82b092037f140d9ee09/.circleci/config.yml#L1)):*
> ```YAML
> version: 2
> ```

Yay!

---

*[.circleci/config.yml, line 36 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-KyXh-PwcT81nIHuklB-:-KyXh-PwcT81nIHuklB0:be01dev) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/353d601959c3dd3c9f6bb82b092037f140d9ee09/.circleci/config.yml#L36)):*
> ```YAML
>       - run:
>           name: Test
>           command: |
> ```

Can you add back `python --version` and `flake8 --version`? They're useful for debugging differences between local & circle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-:-KyXg6oX_n8rkFlm5Cqg:b64wovw)*

**Comment by alexeisw** [comment]
Thats great. As we created https://github.com/sidewalklabs/doppelganger-internal  for internal work (including Toronto), does this need to be replicated there too? :-/ 

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-:-KyXpo2wcuh0PW7GGPJq:b-1wmjli)*

**Comment by bnaul** [comment]
I didn't know that fork existed but it's an easy change to make there too.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[requirements.txt, line 4 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-KyXgEc35fyBi-EXM5Y5:-KyXr8PnR-6R_VC6m_bB:bfblgyp) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/353d601959c3dd3c9f6bb82b092037f140d9ee09/requirements.txt#L4)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Do we still need to pin the version?  I guess future ones won't have wheels
</blockquote></details>

I set up the wheels to build automatically when he does a release so it should be fine; changing to >=.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-:-KyXrGbv9-BMas8CXG-j:bjvmyii)*

**Comment by bnaul** [comment]
Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50)*

**Comment by bnaul** [comment]
This should be good to go :lgtmyself:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-:-KyY9LGgqcChsQTKrASM:b-iyjkhy)*

**Comment by katbusch** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 36 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-KyXh-PwcT81nIHuklB-:-KyYACxkGP9JMpbYTLan:b-7l3ba0) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/353d601959c3dd3c9f6bb82b092037f140d9ee09/.circleci/config.yml#L36)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Can you add back `python --version` and `flake8 --version`? They're useful for debugging differences between local & circle
</blockquote></details>

ping?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50)*

**Comment by katbusch** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/50#-:-KyYAQaD3duZ_k_EcSOV:bnfp4nl)*

**Pull request merged**
